'use client';

import { useState, useRef, useEffect } from 'react';
import { ChevronUp, ChevronDown } from 'lucide-react';

export default function VideoTestimonialPage() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isMobile, setIsMobile] = useState(false);
  const videoRef = useRef(null);
  const carouselRef = useRef(null);
  const [isAutoScrolling, setIsAutoScrolling] = useState(true);

  const testimonials = [
    {
      id: 1,
      name: 'Luna Voss',
      role: 'AI ETHICS OFFICER',
      badge: 'AI UPDATE',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=800&h=600&fit=crop',
      description: 'Generated by AI • 5 mins ago'
    },
    {
      id: 2,
      name: 'Kai Zen',
      role: 'LEAD DEVELOPER',
      badge: 'AI INSIGHT',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop',
      description: 'Generated by AI • 8 mins ago'
    },
    {
      id: 3,
      name: 'Nova Rex',
      role: 'COMMUNITY LEAD',
      badge: 'SMART NEWS',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800&h=600&fit=crop',
      description: 'Generated by AI • 12 mins ago'
    },
    {
      id: 4,
      name: 'Alex Rivera',
      role: 'CEO & FOUNDER',
      badge: 'AI INSIGHT',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&h=600&fit=crop',
      description: 'Generated by AI • 15 mins ago'
    },
    {
      id: 5,
      name: 'Maya Chen',
      role: 'DESIGN DIRECTOR',
      badge: 'AI UPDATE',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
      description: 'Generated by AI • 18 mins ago'
    },
    {
      id: 6,
      name: 'James Park',
      role: 'TECH INNOVATOR',
      badge: 'SMART NEWS',
      badgeColor: 'bg-gradient-to-r from-pink-500 to-red-500',
      videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=600&fit=crop',
      description: 'Generated by AI • 22 mins ago'
    }
  ];

  // Triple the array for infinite scroll effect
  const infiniteTestimonials = [...testimonials, ...testimonials, ...testimonials];

  // Check if mobile
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 1024);
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  // Auto-scroll carousel (only on desktop)
  useEffect(() => {
    if (!isAutoScrolling || isMobile) return;

    const interval = setInterval(() => {
      if (carouselRef.current) {
        const scrollHeight = carouselRef.current.scrollHeight / 3;
        carouselRef.current.scrollTop += 1;

        // Reset to middle section when reaching the end
        if (carouselRef.current.scrollTop >= scrollHeight * 2) {
          carouselRef.current.scrollTop = scrollHeight;
        }
      }
    }, 30);

    return () => clearInterval(interval);
  }, [isAutoScrolling, isMobile]);

  // Handle video end - play next video
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleVideoEnd = () => {
      setCurrentIndex((prev) => (prev + 1) % testimonials.length);
    };

    video.addEventListener('ended', handleVideoEnd);
    return () => video.removeEventListener('ended', handleVideoEnd);
  }, [testimonials.length]);

  // Load and play video when index changes
  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.load();
      videoRef.current.play();
    }
  }, [currentIndex]);

  const handlePrevious = () => {
    setCurrentIndex((prev) => (prev === 0 ? testimonials.length - 1 : prev - 1));
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev === testimonials.length - 1 ? 0 : prev + 1));
  };

  const handleThumbnailClick = (index) => {
    setCurrentIndex(index % testimonials.length);
  };

  return (
    <div className="min-h-screen bg-linear-to-br from-[#0f0020] via-[#1a0033] to-[#0f0f1e]  p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto h-screen">
        <h1 className="text-3xl sm:text-4xl lg:text-5xl pb-10 text-center  font-bold text-white mb-6 mt-20 md:mb-12">Client Testimonials</h1>
        
        <div className="flex flex-col lg:flex-row gap-4 lg:gap-6">
          {/* Left side - Big video player */}
          <div className="w-full lg:flex-1 relative rounded-2xl lg:rounded-3xl overflow-hidden bg-black/30 backdrop-blur-sm" style={{ height: isMobile ? '400px' : 'calc(100vh - 250px)' }}>
            <video
              ref={videoRef}
              className="w-full h-full object-cover"
              controls
              autoPlay
              muted
              src={testimonials[currentIndex].videoUrl}
            />
            
            <div className="absolute top-4 left-4 lg:top-6 lg:left-6">
              <span className={`${testimonials[currentIndex].badgeColor} text-white text-xs font-bold px-3 py-1.5 lg:px-4 lg:py-2 rounded-full uppercase tracking-wide`}>
                {testimonials[currentIndex].badge}
              </span>
            </div>

            <div className="absolute bottom-0 left-0 right-0 bg-linear-to-t from-black/90 via-black/50 to-transparent p-4 lg:p-8">
              <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-white mb-1 lg:mb-2">{testimonials[currentIndex].name}</h2>
              <p className="text-sm lg:text-lg text-gray-300 uppercase tracking-wider">{testimonials[currentIndex].role}</p>
              <p className="text-xs lg:text-sm text-gray-400 mt-1 lg:mt-2">{testimonials[currentIndex].description}</p>
            </div>
          </div>

          {/* Mobile - Horizontal carousel */}
          {isMobile && (
            <div className="w-full mt-13 h-fit ">
              <div 
                className="flex gap-3 overflow-x-auto pt-4 pb-2 snap-x snap-mandatory hide-scrollbar"
                style={{ scrollBehavior: 'smooth' }}
              >
                {testimonials.map((testimonial, index) => {
                  const isActive = index === currentIndex;
                  
                  return (
                    <div
                      key={testimonial.id}
                      onClick={() => handleThumbnailClick(index)}
                      className={`relative rounded-xl overflow-hidden cursor-pointer transition-all duration-300 shrink-0 snap-center ${
                        isActive
                          ? 'ring-4 ring-pink-500 scale-105'
                          : 'opacity-70'
                      }`}
                      style={{ width: '240px', height: '140px' }}
                    >
                      <div 
                        className="absolute inset-0 bg-cover bg-center"
                        style={{ backgroundImage: `url(${testimonial.thumbnail})` }}
                      />
                      <div className="absolute inset-0 bg-linear-to-t from-black/80 via-black/40 to-transparent" />
                      
                      <div className="absolute top-2 left-2">
                        <span className={`${testimonial.badgeColor} text-white text-xs font-bold px-2 py-1 rounded-full uppercase tracking-wide`}>
                          {testimonial.badge}
                        </span>
                      </div>

                      <div className="absolute bottom-2 left-2 text-white">
                        <h3 className="text-base font-bold mb-0.5">{testimonial.name}</h3>
                        <p className="text-xs uppercase tracking-wider text-gray-300">{testimonial.role}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Desktop - Vertical carousel */}
          {!isMobile && (
            <div className="w-80 flex flex-col gap-4" style={{ height: 'calc(100vh - 250px)' }}>
              <button
                onClick={handlePrevious}
                className="w-full bg-white/10 hover:bg-white/20 backdrop-blur-sm rounded-2xl p-3 flex items-center justify-center transition-all"
              >
                <ChevronUp className="w-6 h-6 text-white" />
              </button>

              <div 
                ref={carouselRef}
                className="flex-1 flex flex-col gap-4 overflow-hidden"
                style={{ scrollBehavior: 'smooth' }}
                onMouseEnter={() => setIsAutoScrolling(false)}
                onMouseLeave={() => setIsAutoScrolling(true)}
              >
                {infiniteTestimonials.map((testimonial, index) => {
                  const actualIndex = index % testimonials.length;
                  const isActive = actualIndex === currentIndex;
                  
                  return (
                    <div
                      key={`${testimonial.id}-${index}`}
                      onClick={() => handleThumbnailClick(index)}
                      className={`relative rounded-2xl overflow-hidden cursor-pointer transition-all duration-300 shrink-0 ${
                        isActive
                          ? 'ring-4 ring-pink-500 scale-105'
                          : 'hover:scale-102 opacity-70 hover:opacity-100'
                      }`}
                      style={{ minHeight: '180px' }}
                    >
                      <div 
                        className="absolute inset-0 bg-cover bg-center"
                        style={{ backgroundImage: `url(${testimonial.thumbnail})` }}
                      />
                      <div className="absolute inset-0 bg-linear-to-t from-black/80 via-black/40 to-transparent" />
                      
                      <div className="absolute top-3 left-3">
                        <span className={`${testimonial.badgeColor} text-white text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wide`}>
                          {testimonial.badge}
                        </span>
                      </div>

                      <div className="absolute bottom-3 left-3 text-white">
                        <h3 className="text-xl font-bold mb-1">{testimonial.name}</h3>
                        <p className="text-xs uppercase tracking-wider text-gray-300">{testimonial.role}</p>
                      </div>

                      {isActive && (
                        <div className="absolute inset-0 border-4 border-pink-500 rounded-2xl pointer-events-none" />
                      )}
                    </div>
                  );
                })}
              </div>

              <button
                onClick={handleNext}
                className="w-full bg-white/10 hover:bg-white/20 backdrop-blur-sm rounded-2xl p-3 flex items-center justify-center transition-all"
              >
                <ChevronDown className="w-6 h-6 text-white" />
              </button>
            </div>
          )}
        </div>
      </div>

      <style jsx>{`
        .hide-scrollbar::-webkit-scrollbar {
          display: none;
        }
        .hide-scrollbar {
          -ms-overflow-style: none;
          scrollbar-width: none;
        }
      `}</style>
    </div>
  );
}